// constants/trip.constants.js

export const TRIP_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  COMPLETED: "COMPLETED",
  WAITING_FOR_DRIVER: "WAITING_FOR_DRIVER",
};

export const TRIP_TYPE = {
  COMPANY: "COMPANY_TRIP",
  INDEPENDENT: "INDEPENDENT_TRIP",
};

export const ROLES = {
  USER: "USER",
  DRIVER: "DRIVER",
  ADMIN: "ADMIN",
};

export const TRIP_MODE = {
  SINGLE: "SINGLE",
  MULTI_STOP: "MULTI_STOP",
  DISTRIBUTION: "DISTRIBUTION",
  RETURN_TRIP: "RETURN_TRIP",
};

export const TRIP_STOP_STATUS = {
  PENDING: "PENDING",
  ARRIVED: "ARRIVED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
};

export const TRIP_STOP_TYPE = {
  PICKUP: "PICKUP",
  DROP: "DROP",
};
